[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--no-as-needed", "-C", "link-arg=-ldl"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,--no-as-needed", "-C", "link-arg=-ldl"]
